os: osx
osx_image: xcode13.3.1
language: swift
script:
  - xcodebuild clean build test -workspace RSSFeed.xcworkspace -scheme "RSSFeed" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO
